name: PocketVote
main: ProjectInfinity\PocketVote\PocketVote
version: 5.0.0
api: [5.0.0]
author: ProjectInfinity
permissions:
  pocketvote.admin:
    description: "Allows player to manage PocketVote"
    default: op
  pocketvote.vote:
    description: "Allows a player to use the /vote command"
    default: true
