CREATE TABLE IF NOT EXISTS `pocketvote_votes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `player` VARCHAR(50) NULL DEFAULT NULL,
  `ip` VARCHAR(255) NULL DEFAULT NULL,
  `site` VARCHAR(255) NULL DEFAULT NULL,
  `timestamp` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB
;